name: task_2
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.8.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  build: ^2.4.1
  source_gen: ^1.4.0
